before:
  hooks:
    - make docs

env:
  - HEROKU_APP_NAME={{ if index .Env "HEROKU_APP_NAME"  }}{{ .Env.HEROKU_APP_NAME }}{{ else }}default-app-name{{ end }}

builds:
  - id: pgconfigctl
    binary: pgconfigctl
    main: cmd/pgconfigctl/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/pgconfig/api/pkg/version.Tag={{.Version}}
      - -X github.com/pgconfig/api/pkg/version.Commit={{.Commit}}

  - id: api
    binary: api
    main: cmd/api/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/pgconfig/api/pkg/version.Tag={{.Version}}
      - -X github.com/pgconfig/api/pkg/version.Commit={{.Commit}}
nfpms:
  - id: default
    package_name: pgconfigctl
    file_name_template: >-
      {{ .Binary }}-
      {{ .Version }}-
      {{- if eq .Os "darwin" }}MacOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}-
      {{ .Arch }}

    builds:
      - pgconfigctl

    homepage: https://pgconfig.org/
    maintainer: Sebastian Webber <sebastian@pgconfig.org>
    description: CLI for the pgconfig.org website

    license: MIT

    formats:
      - deb
      - rpm

archives:
  - id: pgconfigctl
    builds:
      - pgconfigctl
    name_template: >-
      {{ .Binary }}-
      {{ .Version }}-
      {{- if eq .Os "darwin" }}MacOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}-
      {{ .Arch }}
    format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*(feat|chore)[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

dockers:
  - dockerfile: cmd/pgconfigctl/Dockerfile
    ids:
      - pgconfigctl
    goarch: amd64
    image_templates:
      - "docker.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - dockerfile: cmd/pgconfigctl/Dockerfile
    ids:
      - pgconfigctl
    goarch: arm64
    image_templates:
      - "docker.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

  - dockerfile: cmd/api/Dockerfile
    goarch: arm64
    ids:
      - api
    image_templates:
      - "docker.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/api:arm64-v{{ .Commit }}"

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

    extra_files:
      - rules.yml
      - pg-docs.yml
  - dockerfile: cmd/api/Dockerfile
    goarch: amd64
    ids:
      - api
    image_templates:
      - "docker.io/pgconfig/api:amd64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/api:amd64-v{{ .Commit }}"
      - "registry.heroku.com/{{ .Env.HEROKU_APP_NAME }}/web:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - rules.yml
      - pg-docs.yml
docker_manifests:
  - name_template: docker.io/pgconfig/api:v{{ .Tag }}
    image_templates:
      - "docker.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "docker.io/pgconfig/api:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "docker.io/pgconfig/api:v{{ .Major }}"
    image_templates:
      - "docker.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "docker.io/pgconfig/api:latest"
    image_templates:
      - "docker.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "docker.io/pgconfig/pgconfigctl:v{{ .Tag }}"
    image_templates:
      - "docker.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
  - name_template: "docker.io/pgconfig/pgconfigctl:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
  - name_template: "docker.io/pgconfig/pgconfigctl:v{{ .Major }}"
    image_templates:
      - "docker.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
  - name_template: "docker.io/pgconfig/pgconfigctl:latest"
    image_templates:
      - "docker.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "docker.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
  - name_template: ghcr.io/pgconfig/api:v{{ .Tag }}
    image_templates:
      - "ghcr.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "ghcr.io/pgconfig/api:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "ghcr.io/pgconfig/api:v{{ .Major }}"
    image_templates:
      - "ghcr.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "ghcr.io/pgconfig/api:latest"
    image_templates:
      - "ghcr.io/pgconfig/api:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/api:amd64-v{{ .Commit }}"
  - name_template: "ghcr.io/pgconfig/pgconfigctl:v{{ .Tag }}"
    image_templates:
      - "ghcr.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
  - name_template: "ghcr.io/pgconfig/pgconfigctl:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
  - name_template: "ghcr.io/pgconfig/pgconfigctl:v{{ .Major }}"
    image_templates:
      - "ghcr.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
  - name_template: "ghcr.io/pgconfig/pgconfigctl:latest"
    image_templates:
      - "ghcr.io/pgconfig/pgconfigctl:arm64-v{{ .Commit }}"
      - "ghcr.io/pgconfig/pgconfigctl:amd64-v{{ .Commit }}"
