on: ["push", "pull_request"]

name: Test Coveralls Parallel

jobs:
  build:
    env:
      CGO_ENABLED: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: make build
  test:
    needs: build
    env:
      CGO_ENABLED: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: make test
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make goveralls-push
